kind = "web"
previewPath = "/"
title = "Milliocare"
version = "1.0.0"
id = "artifacts/milliocare"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22602

[services.development]
run = "pnpm --filter @workspace/milliocare run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/milliocare", "run", "build" ]
publicDir = "artifacts/milliocare/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22602"
BASE_PATH = "/"
